### ISSUE TITLE
Ignition Tank not applying to Arsonist skills

### ISSUE THREAD

**Issue by aintnobodyexistinghere** [Popcorn-Factory/Arsonist-RoR2#1]
See title. Arsonist Primary and Utility skills apply Ignite instead of Stronger Burn when an Ignition Tank is in the inventory. For the sake of testing, I also collected a Molotov (6-Pack) which DID apply Stronger Burn.

Edit: Correction, it appears that his Primary skill DOES apply Stronger Burn. His Secondary doesn't apply any status effect at all, I have no idea why I thought it did. His utility does NOT apply Stronger Burn however.

**Comment by Ethanol10** [comment]
Hi, sorry I didn't look into this earlier!

I'll have a look when I can and will address this in the next update.

**Comment by Ethanol10** [comment]
This should be fixed, closing.
