### ISSUE TITLE
Bugs found in 2.0

### ISSUE THREAD

**Issue by Arch-Noize** [Popcorn-Factory/Arsonist-RoR2#10]
### Zero Point Blast gets increased cooldown after overheating
I couldn't find on the patch notes that this was an intended change (and if it is.... It would be _very_ bad design). Here's the cooldown of the Zero Point Blast according to the character selection screen.
![image](https://github.com/Popcorn-Factory/Arsonist-RoR2/assets/91759364/c7855456-9e54-4935-9d2c-192d5f71e065)

However, in game it is actually 7 seconds.
![image](https://github.com/Popcorn-Factory/Arsonist-RoR2/assets/91759364/3bdaf006-b9c9-4aff-b1c4-fbeeebf8aba8)

..... Until you overheat.
![image](https://github.com/Popcorn-Factory/Arsonist-RoR2/assets/91759364/9d38c0fe-85e8-4d99-add6-70e40a7b2036)

After you overheat even once, your Zero Point Blast goes on cooldown for 'the correct amount' for the entirety of the stage. Even if this dash does good damage, its extremely short even with Cleanse movement speed and is heavily unreliable to use for damage. It works better as a dash so, I suggest:
- Please fix the bug so that it has a constant cooldown at all times, 
- Keep the cooldown at 7 seconds, if you can.
- Maybe give it better utility as a dash but less damage?

### Cleanse cooldown still increases if you are under its effects but overheat.
AKA, if you use Masochism and go into Overheat by the time the buff Cleanse gives, you still get the 18s cooldown

### Weird jump being stuffed bug
Sometimes when you fire Fireball while jumping, you 'bump' with something on the air. Making your jump stuffed and sent back to the floor. Like Issue #6 said basically.

### Still triggers Pyromania self-burn when opening void crates or blood altar, even though you have Safer Spaces
The title explains itself.

I can try record these instances but my machine is a bit funky when recording (I am on a Linux machine, using OBS)

**Comment by Ethanol10** [comment]
Thanks for the detailed bug report! I will take a look at it when I get the time!

**Comment by Ethanol10** [comment]
Hi there, I've attempted to fix all these issues in 2.1.1, please have a look!
