### ISSUE TITLE
Newly found bugs in 2.1.1

### ISSUE THREAD

**Issue by Arch-Noize** [Popcorn-Factory/Arsonist-RoR2#11]
Hi again, lol sorry.

I am just testing out as I'm writing this out and I really like all the changes you've done, plus thanks for fixing all the bugs from #10! I found two new ones though aaaaaa (also programmer so I know this pain).

### ZPB disables flamethrower when on Overheat? (Can't confirm)
I couldn't replicate this one but there was a... weird... visual bug? Basically, I went to overheat, used ZPB, and after I did that... I couldn't use flamethrower for the rest of the overheat. I say its a visual bug because the fire SFX was sounding and somehow I was also able to ignite enemies... but not damage them. What's weirder is that it happened only—and I mean _only_—on the first stage, after I fought the boss. Tried replicating it through several levels so far... nothing

### Overheat Cleanse window seems a bit broken
If you cleans to remove Overheat 'too soon' now, you get the SFX, you get the increased CD... but no Cleanse actually happens. I say 'too soon' in quotations because I can overheat, wait half a second, cleanse, and it still breaks. 
Managed to get a screenshot of this.
![image](https://github.com/Popcorn-Factory/Arsonist-RoR2/assets/91759364/25f33f95-aebd-450d-8f1e-3686544c50f5)

### Backup Mag and extended cooldown interaction
If you have, say, Backup Mag and gain an extended cooldown, if you cast the skill again, it reduces whatever the cooldown may be back to their normal cooldown. Basically, I overheat, use ZPB get extended cooldown, I use it again thanks to backup mag, cooldown goes from 8s to 3s. 
I have heard this is a mess of a bug as a whole with how ROR2 interacts with changed cooldowns and being able to cast multiple times that same skill. Not sure how you can indeed 'store' the value of the time you got an extended cooldown whilst also storing the cooldown of the same skill, but reduced

**Comment by Crypto-Spartan** [comment]
Just tested - Dragon's Breath with the normal gauge works as intended

**Comment by Ethanol10** [comment]
Oh boy back to the keyboard haha

Thanks for the bug report I'll try fix them as soon as I can!

Not sure if I can fix the backup mag issue though. The Cooldown only changes when you use the skill either in overheat or non-overheat, so if you use the skill while it's in overheat, you'll get an extended cooldown, but if you use it again (in the case of backup magazine), the skill changes the cooldown to the lower one. This is probably intended and won't be changed.

I'll try fix the Cleanse issue for sure, but I'll have to see where the ZPB one goes, as I'm not sure about the replication method

**Comment by Ethanol10** [comment]
Since the other two I will not attempt to fix This is considered closed. 

Please check out 2.1.2!
