### ISSUE TITLE
Supercritical gauge not increasing with level in 2.1.1

### ISSUE THREAD

**Issue by Crypto-Spartan** [Popcorn-Factory/Arsonist-RoR2#12]
Hi! I love the Arsonist, super fun survivor to play. I tried out the Dragon's Breath primary with the Supercritical Gauge (not sure if the bug is specific to that combo), but as I leveled up, the blue portion of my gauge was not growing any larger. You can see in my screenshot that I'm level 15, but the blue portion of the gauge is the same as stage 1 level 1. 

If there's any testing or feedback you'd like from me, please let me know. Thanks again for the mod!

![20231205150110_1](https://github.com/Popcorn-Factory/Arsonist-RoR2/assets/29098151/ced23ffa-7332-4118-82aa-86c123ae9339)

**Comment by Crypto-Spartan** [comment]
Just tested - Dragon's Breath with the normal gauge works as intended

**Comment by Ethanol10** [comment]
Hi there, Blue Gauge does not increase with stock items or levels, only normal gauge does. This is intended!

**Comment by Ethanol10** [comment]
However, if you have stock items, it increases the blue portion of the gauge!

**Comment by Ethanol10** [comment]
Stock items specifically are the ones that increase the amount of stocks you have on your abilities, a.k.a, Backup magazine, Lysate cell, headlight afterburner etc.The supercritical gauge only increases the range in which blue is active, not the actual amount of heat. So if at no upgrades the bar only has, 35% blue, it you get some items that give you stocks for your abilities it will increase the overall percentage of the bar higher than 35%.

**Comment by Crypto-Spartan** [comment]
so Backup Mags for example would increase the amount of blue? thanks!

**Comment by Ethanol10** [comment]
You're right, i'll get it changed.
