### ISSUE TITLE
ArsonistController.Start() can sometimes fail causing NullRefs in EnergySystem.Update().

### ISSUE THREAD

**Issue by WolfoIsBestWolf** [Popcorn-Factory/Arsonist-RoR2#15]
I can't replicate this issue with the respawn command or Dios only with a delayed respawn I use in my mods, but I feel if my mods break it and what I do is fine for every other character I've encountered then maybe it's more an issue here since other mods might break it too. 

Also I'm pretty sure this can easily break with latency but cant test that.

I suggest changing : 

            ChildLocator childLocator = GetComponentInChildren<ChildLocator>();
            if(childLocator != null)
            { 
			
			
			
to 

            ChildLocator childLocator = GetComponentInChildren<ChildLocator>();
            if(childLocator == null)
            { 
			childLocator = GetComponent<ModelLocator>().modelTransform.GetComponent<ChildLocator>();
		}		
		if(childLocator != null)
            { 

as a additional safety check

**Comment by Ethanol10** [comment]
Man that's wack. I'll try out that fix

**Comment by Ethanol10** [comment]
changed to pull from modeltransform instead of finding component in children.
