### ISSUE TITLE
Arsonist Auto-dies from burn that keeps ticking from a blood shrine.

### ISSUE THREAD

**Issue by MoistCerealII** [Popcorn-Factory/Arsonist-RoR2#16]
title
![Uploading 20240220170531_1.jpg…]()

**Comment by Ethanol10** [comment]
Seems to work as intended, what particularly are you finding issue with? Does arsonist die instantly?

**Comment by Ethanol10** [comment]
Considering if it's a 50% shrine, it'll do 25% damage as usual, then do arsonist's passive for 25% of the rest of the damage as fire. This effect is exaggerated when taking 90% of your health, with 45% of your health being taken, then the other 45% as fire damage.
