### ISSUE TITLE
I think the fire sfx might be a bit too loud

### ISSUE THREAD

**Issue by DamageMaximo** [Popcorn-Factory/Arsonist-RoR2#17]
I think the fire sfx might be a bit too loud, please add a config to adjust how loud the volume is, thank you!

**Comment by Ethanol10** [comment]
Hi there, 

I'll have a look into getting that done.

**Comment by Ethanol10** [comment]
I've added a universal SFX volume slider in the config that can be edited through Risk of options. Please have a look!
