### ISSUE TITLE
Fireball issues with AttackDirectionFix

### ISSUE THREAD

**Issue by Expakun** [Popcorn-Factory/Arsonist-RoR2#18]
If you use the AttackDirectionFix Mod with Arsonists Fireball, it will come out of your crosshair.
I know that this is what the mod does, and I prefer it that way for every other Survivor, but I feel like it does not work very well with Arsonist.

If it is possible, I would like it if Arsonist would not be affected by AttackDirectionFix

**Comment by Ethanol10** [comment]
Hi there, 
I can't really change how the mod affects the Arsonist, as it changes the fundamental functionality of all mods that use projectiles. 

Sorry about that.
