### ISSUE TITLE
Arsonist flies away when thrown by SS2 Chirr and running CustomEmotesApi

### ISSUE THREAD

**Issue by LordVGames** [Popcorn-Factory/Arsonist-RoR2#19]
Very specific, yes, but it's true. AFAIK this only affects Arsonist. Turning off CustomEmotesApi lets Arsonist get grabbed and thrown just fine. He gets fixed on stage transition, but trying to throw him again will make him fly away again.

https://github.com/Popcorn-Factory/Arsonist-RoR2/assets/51967559/a81f522a-336f-4f59-81a7-a3b63e7aea64

Nothing seemed weird in the log as well, but here it is anyways:
[LogOutput.log](https://github.com/user-attachments/files/15847560/LogOutput.log)

**Comment by Ethanol10** [comment]
geez lmao how does the grab work? the custom emote skeleton shouldn't have any colliders on it to cause major issues.

**Comment by Ethanol10** [comment]
Unsure how to fix, Will not fix right now.
