### ISSUE TITLE
Arsonist crashing the game at Character Select Menu (Seekers of the Storm)

### ISSUE THREAD

**Issue by Aaron00000** [Popcorn-Factory/Arsonist-RoR2#20]
Downloaded the latest version that said it was compatible with SotS, but the game crashes as soon as it tries to load the character menu. 
[LogOutput.log](https://github.com/user-attachments/files/16824993/LogOutput.log)

**Comment by Aaron00000** [comment]
Got some info from Moffein about the issue, apparently occurs when old mods are loaded, even base mods that are pre-SotS that are used by mods updated after SotS.

**Comment by Ethanol10** [comment]
If your problem is solved, I'll close this issue.
