### ISSUE TITLE
SS2 Typhoon fails ot unlock Grandmastery skin

### ISSUE THREAD

**Issue by Ceephalon** [Popcorn-Factory/Arsonist-RoR2#21]
as per title, Ive made a few attempts with the character with both celestial portal and mithrix kills under belt, neither of witch have unlocked the skin proper. the mithrix kills have happened ot be while i was connected to another host however, and outside of "cheating" to get the skin its hard to collaberate if that was the issue, Game version is most recent at time of writing, with all DLC's

**Comment by Ethanol10** [comment]
hmm, might be an issue with how the achievements are granted, i'll test it later.

**Comment by Ethanol10** [comment]
This is confirmed to be an issue with the achievement, I will update you when it is fixed

**Comment by Ethanol10** [comment]
Should be fixed as of 2.2.2.
