### ISSUE TITLE
request a language token

### ISSUE THREAD

**Issue by ggang-b** [Popcorn-Factory/Arsonist-RoR2#3]
Thank you for creating a great mode. I request a language token because I want to translate the mode. Is it possible?

**Comment by Ethanol10** [comment]
Hi, sorry I didn't see this earlier! 

The language tokens can be found in the Token.cs file, if you need some more information on this let me know.

https://github.com/Popcorn-Factory/Arsonist-RoR2/blob/master/ArsonistMod/Modules/Tokens.cs

**Comment by Ethanol10** [comment]
Following up on this, there will most likely be an update for this mod that adds new skills and such, which may require more translation work. Just a heads up!

**Comment by Ethanol10** [comment]
If you're wondering, the DEVELOPER_PREFIX is `POPCORN`.

This means the full token should end up looking like `POPCORN_ARSONIST_BODY_LORE` if it's the lore entry.

**Comment by Ethanol10** [comment]
Nothing to fix here. Closing ticket.
