### ISSUE TITLE
Fireball primary halts Arsonist's upward momentum when aimed downwards.

### ISSUE THREAD

**Issue by Aaron00000** [Popcorn-Factory/Arsonist-RoR2#6]
Aiming beyond a certain angle downwards and firing a Fireball completely halts Arsonist's upwards momentum. Tested with no mods other than Arsonist active, Dragon's Breath does not have this issue;
[LogOutput.log](https://github.com/Popcorn-Factory/Arsonist-RoR2/files/13480335/LogOutput.log)

**Comment by Ethanol10** [comment]
Hi there, i've mitigated the issue in v2.1.1, this may still occur, but it should be less prominent.
