### ISSUE TITLE
Arsonist model appears bright orange to multiplayer clients other than self

### ISSUE THREAD

**Issue by starshallows** [Popcorn-Factory/Arsonist-RoR2#7]
i'm unsure if this affects alt skins other than the firebug since i didn't think to test it further with pals before they stopped, but across multiple runs, with multiple friends, from the exact beginning of every run, the model for the arsonist is stuck as a jarring bright orange. this is also a relatively CLEAN install, with no other mods installed other than what's needed to run it!

it's a very small issue, but an issue nonetheless! thank u for ur time 🙏

![brightbug](https://github.com/Popcorn-Factory/Arsonist-RoR2/assets/152241817/7e282602-084a-46aa-91a1-d5101d158d6c)

**Comment by Ethanol10** [comment]
Thanks for the bug report, will look into it!

**Comment by Ethanol10** [comment]
Should be fixed in 2.1.3, open a new issue if this still occurs.
