### ISSUE TITLE
2.0 Problems

### ISSUE THREAD

**Issue by Holneer** [Popcorn-Factory/Arsonist-RoR2#8]
Masochist ability appears to be unavailable even at 5+ stacks at times, doesn't properly heal (I know it's lifesteal) at times (was playing Co-op, not host, so maybe ping but idk).

Wish there was an option for "Legacy" attacks with old effects because new ones just don't feel good, they're too flashy and take too much screenspace.

**Comment by Ethanol10** [comment]
No response, closing ticket.
