### ISSUE TITLE
Dragon's Breath attack speed/tickrate doesn't scale up properly

### ISSUE THREAD

**Issue by Holneer** [Popcorn-Factory/Arsonist-RoR2#9]
It seems that cooling speed adjusts properly to the attack speed items, which cannot be said for Dragon Breath's attack... Judging from what I saw Dragon's Breath attack rate only increases from 25% boosts. Which is 4 Mochas or 2 Syringes. In-betweens that approach the 25% threshold without reaching it demonstrate perfectly how your cooling speed completely overwhelms attack speed, making Supercritical gauge nigh unusable at times. Especially noticeable with 3 syringes. They provide you with 45% (15*3) attack speed, that is 25% attack and 45% cooling which leads you to getting close to no heat at all. Video examples in the link below, uploaded to Imgur because github has a 10 MB file limit.

https://imgur.com/a/oXQyq2u

**Comment by Ethanol10** [comment]
Yeah, we're looking into fixing the scaling with the heat consumption and cooling rate on dragon's breath, it may take awhile. Thanks for the report!
